### PR TITLE
feat: strokeDasharray with Animated

### PR DESCRIPTION
**Pull request by WoLewicki**
# Summary

PR adding the proper handling of `strokeDasharray` prop for when used with `Animated`. Code based on https://github.com/software-mansion/react-native-svg/pull/1464 by @bardliu, but with the newest state of the repository.

## Test Plan

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md`
- [ ] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Comment by WoLewicki** [comment]
@pavel-stryber could you check if applying this PR fixes your problems with `Animated` and components with `strokeDasharray`?

**Comment by pavel-stryber** [comment]
I have added small changes to example. Changed animation implementation from plain react native to 'react-native-reanimated'. Also, changed testing component. I guess, you incidentally set `ColorTest` component .
Tested on iOS and Android, all works fine now.

Here my PR for reference: https://github.com/software-mansion/react-native-svg/pull/2090

**Comment by WoLewicki** [comment]
Ok thanks, I updated the example. Also, I want to keep the `ColorTest` example as the default one so it is not the case here. I'll close your PR not to duplicate the changes. Thanks for your contribution :rocket:

**Comment by pavel-stryber** [comment]
Big thanks @WoLewicki, I didn't expect how fast it was.

**Pull request merged**
