### PR TITLE
fix #1592 : add marker support on Rect, Line, Ellipse, Circle and Group

### LINKED ISSUE #1592: Marker - display issues on android
# Bug

I am using `Markers`, it works well on iOS, but on Android markers are only displayed on `<Path/>` (I can't see them on `<Line/>`, `<Ellipse/>` and `<Rectangle/>`)

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
System:
    OS: macOS 11.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 97.19 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0
      System Images: android-22 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-R | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_262 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.1 => 0.64.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 12.1.1

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

1. git clone https://github.com/mlecoq/svg-draw
2. cd svg-draw
3. yarn
4. yarn start

Describe what you expected to happen:

1. Use pen to draw on picture (you see the markers in blue on both iOS and android) 
2. Use line, rect or circle (no marker on android but it works on iOS)

### PR DESCRIPTION
**Pull request by mlecoq**
# Summary

Explain the **motivation** for making this change: here are some points to help you:

* What issues does the pull request solve? Please tag them so that they will get automatically closed once the PR is merged
#1592
* What is the feature? (if applicable)

   Markers on `Line`, `Rect`, `Ellipse`, `Circle` and `Group`

* How did you implement the solution?

  Markers were only displayed on `Path` on Android. I have looked at the code and `Markers` are based on `elements` attribute which was only filled via `PathParser`. I have modified `getPath` method on other shapes in order to fill `elements` attribute. For groups I only copied data from children. 

* What areas of the library does it impact?

  Only Android is impacted, markers are now displayed on `Rect`, `Line`, `Ellipse`, `Circle` and `Group`

## Test Plan

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### What's required for testing (prerequisites)?

none

### What are the steps to reproduce (after prerequisites)?

Create a svg with a marker, for example on a rectangle 

```
<Svg width="400" height="200" viewBox="0 0 4000 2000">
  <Defs>
    <Marker
      id="selection"
      markerUnits={'userSpaceOnUse' as MarkerUnits}
      refX="0"
      refY="0"
       orient="auto"
    >
     <Circle
            fill="#3a6cff"
            r={5}
            cx={0}
            cy={0}
            strokeWidth={1}
            stroke="white"
          />
    </Marker>
  </Defs>
  <Rect
    x="10"
    y="10"
    width="3980"
    height="1980"
    fill="none"
    stroke="blue"
    strokeWidth="10"
   marker="url(#selection)"
  />
</Svg>
```

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     | (it worked already fine on iOS)
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md` 
- [ ] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Review by syedquadri1982 — APPROVED** [review]

**Comment by somasekharkakarla** [comment]
@mlecoq  marker still does not work. please test it once your end.
Platfrom: Android 
Lib.version: 12.3.0

Please resolve this as soon as possible.

**Comment by mlecoq** [comment]
the PR is not yet merged, can you test with ` "react-native-svg": "mlecoq/react-native-svg#hotfix/displayMarkersOnAndroid",` ?

**Comment by somasekharkakarla** [comment]
@mlecoq yeah sure

**Comment by somasekharkakarla** [comment]
npm i git@github.com:mlecoq/react-native-svg.git#hotfix/displayMarkersOnAndroid
unable to install

**Comment by somasekharkakarla** [comment]
i tried to change same files in original libs folder for line and group. Still marker didn't work
Screenshot 2022-04-16 at 4 07 16 PM

**Comment by mlecoq** [comment]
Can you share your example ?

**Comment by somasekharkakarla** [comment]
hi @mlecoq ,
here is the example https://github.com/somasekharkakarla/svg_test_react_native
By the way i am trying to implement same as your svg-draw.

**Comment by mlecoq** [comment]
Thanks !

**Comment by somasekharkakarla** [comment]
Hi @mlecoq any update?

**Comment by mlecoq** [comment]
I'm on vacation 😄, next week !

**Comment by somasekharkakarla** [comment]
@mlecoq enjoy vacation. Your solution worked. i just reset my cache and re started my laptop it worked. Thank you bro.
Why still PR not merge with main library?

**Comment by WoLewicki** [comment]
I believe it was not added since the `svg` standard does not support markers for those elements: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker. Or am I missing something?

**Comment by mlecoq** [comment]
Hi @WoLewicki 

Thanks for your feedback 

If we look at the documentation, markers should be available at least for Line tags.

And on iOS with react-native-svg it works for all of them

**Comment by jake-nz** [comment]
I think this should be merged. True, the SVG spec only has markers for `<path>`, `<line>`, `<polyline>` and `<polygon>` but it's better to merge this PR and support extra elements than the current state where some elements that should be supported are not.

I'm currently facing this issue where my `<Line>`s have no markers
I can use `<Path>` instead but the markers are huge on Android
This PR fixes both issues

**Comment by tmeiss** [comment]
Any plans to merge this?

**Comment by narliecholler** [comment]
merging? O.o

**Comment by WoLewicki** [comment]
I tried using it with percentages instead of numbers for props, and the points seem to be calculated in a wrong way then. Am I missing something?

**Comment by WoLewicki** [comment]
@mlecoq I pushed a fix of those mentioned problems to your fork. Could you merge it to your branch so they are available here?

**Comment by mlecoq** [comment]
@WoLewicki done !

**Review by WoLewicki — APPROVED** [review]
LGTM!

**Pull request merged**
