### PR TITLE
fix: Fixed react imports to work with typescript

### PR DESCRIPTION
**Pull request by bintoll**
# Summary

Explain the **motivation** for making this change: here are some points to help you:

* What issues does the pull request solve? Please tag them so that they will get automatically closed once the PR is merged
#1169  

* What is the feature? (if applicable)
There is no feature

* How did you implement the solution?
Fixed the React imports:
Replaced: import React, { Component } from 'react'
To: import * as React from 'react'

* What areas of the library does it impact?
All *.tsx files

## Test Plan

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### What's required for testing (prerequisites)?
Just add this package in react-native project with typescript
### What are the steps to reproduce (after prerequisites)?
If the old version will be added in react native project with typescript it will lead to "React is not defined" error
## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md` (there is nothing to add because changes do not effect functionality)
- [ ] I updated the typed files (typescript) (no need in it)
- [ ] I added a test for the API in the `__tests__` folder (no need in it)

### CODE REVIEW

**Comment by bintoll** [comment]
Hello! Will it be merged at least in develop brach?

**Comment by msand** [comment]
Yeah, there's a few conflicts that would need resolving first

**Comment by msand** [comment]
Mind rebasing onto the latest commit in the develop branch?

**Comment by bintoll** [comment]
@msand rebased onto the latest commit in develop branch. So ready to merge)

**Comment by bintoll** [comment]
please merge it =)

**Comment by bintoll** [comment]
@msand Hello?

**Comment by bintoll** [comment]
@msand excuse me for disturbing, but did you had a chance to check merge request?

**Comment by WoLewicki** [comment]
@bintoll are you able to update this PR with the newest state of the repo?

**Comment by bintoll** [comment]
@WoLewicki Sorry, lack of time now

**Pull request closed without merging**
