### PR TITLE
feat: update FabricExample to 0.71.0-rc.6

### PR DESCRIPTION
**Pull request by WoLewicki**
PR bumping examples to RN 0.71. For now web Example seems not to load code properly.

### CODE REVIEW

**Comment by WoLewicki** [comment]
@marlenecota seems like having `react-native-windows` package installed in the app causes Android build to fail on RN 0.71: https://github.com/software-mansion/react-native-svg/actions/runs/3884523601/jobs/6627198822. Is it known behavior and should we do something about it?

**Comment by WoLewicki** [comment]
Ok I bumped the version to `react-native-windows` to `0.71.0-preview.3` and it seems to work correctly. Could you check if the windows example works there too?

**Comment by marlenecota** [comment]
@WoLewicki checked out the PR and the windows example builds and launches fine thanks!

**Comment by curthipster** [comment]
Hi. I've confirmed that this fixes the compilation issues I'm having upgrading to RN 0.71.1. Thank you!

When can we expect it to be released?

**Comment by WoLewicki** [comment]
Release is here: https://github.com/software-mansion/react-native-svg/releases/tag/v13.8.0 :tada:

**Pull request merged**
