### PR TITLE
fix: enable toDataURL for web

### LINKED ISSUE #1358: ref.toDataURL does not exist when using react-native-web
# Bug

[Your example](https://github.com/react-native-community/react-native-svg/issues/855#issuecomment-471371812) is using

```js
onRef = ref => {
    if (ref && !this.state.base64) {
      ref.toDataURL(
        base64 => {
          this.setState({ base64 });
        },
        { width: 200, height: 200 },
      );
    }
  };
```

#### Unexpected behavior

But ref.toDataURL is null

## Steps To Reproduce

1. Go to https://codesandbox.io/s/react-native-svg-test-wlfex
2. See the console.log as I have the following changes

```
<Svg
  xmlns="http://www.w3.org/2000/svg"
  width="275"
  height="200"
  viewBox="0 0 275 200"
  ref={ref => {
    console.log(ref.toDataURL);
    console.log(ref);
  }}
>
```

Describe what you expected to happen:

I can use ref.toDataURL

### PR DESCRIPTION
**Pull request by wood1986**
fix #1358

### CODE REVIEW

**Comment by wood1986** [comment]
Hey @msand and @magicismight Could you please take a look this?

**Comment by wood1986** [comment]
Any update

**Comment by likeSo** [comment]
Any updates about this? Does react-native-svg available on web now?

**Comment by chrispader** [comment]
Unfortunately i can't get your implementation to work. The `img.onload` callback is never triggered in my case. Am i overseeing something here?

**Comment by chrispader** [comment]
@WoLewicki could you might help here? Are there plans on adding the `toDataURL` function to `react-native-svg`?

I can help with the implementation, if you guys plan on adding this functionality :)

**Comment by willhalling** [comment]
I would love to see this working on the web too.

**Comment by chrispader** [comment]
@wood1986 i continued your work on this in [this PR](https://github.com/software-mansion/react-native-svg/pull/2072) and it's now working for me! 🚀

**Comment by WoLewicki** [comment]
Closing since #2072 has been merged. Thanks for your contribution :rocket:

**Comment by chrispader** [comment]
@WoLewicki thanks!

**Pull request closed without merging**
