### PR TITLE
fix: Ensure RNSVG.dll is built with proper publisher/versioning information via new resource file.

### PR DESCRIPTION
**Pull request by taenri**
# Summary

On Windows, `RNSVG.dll` is getting flagged by AppLocker on many of our user's devices because it is missing proper publisher/versioning information in its metadata. This forces users to manually add this DLL to AppLocker's allow-list during some update/installation scenarios.

The `RNSVG.sln` file also currently fails to build from Visual Studio directly, because the `fmt` project is not explicitly included from the `react-native-windows` Node package.

## Test Plan

For testing, I opened `RNSVG.sln` in Visual Studio on Windows (with Node packages installed and other build prerequisites) and built it for `Debug|x64`.

Without my change, building the solution fails to build directly from Visual Studio (since it fails to link fmt.lib when building the Microsoft.ReactNative project). Even when building from the terminal using MSBuild, `RNSVG.dll` properties do not contain proper publisher/versioning details.

With my change, building the solution in Visual Studio succeeds and `RNSVG.dll` contains the correct publisher/versioning details in its properties. These can be viewed via File Explorer.

image

Note that the version constants defined in the `versionoverrides.rc` file will ideally need to be updated whenever the version tracked in package.json is updated. Further changes will be required to make `versionoverrides.rc` account for the `package.json` version automatically. This change is good enough to satisfy AppLocker requirements for now though.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ❌     |
| Windows     |    ✅     |
| MacOS     |    ❌     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md`
- [ ] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Comment by WoLewicki** [comment]
@marlenecota wdyt about this one?

**Review by marlenecota — APPROVED** [review]

**Comment by marlenecota** [comment]
@WoLewicki - looks good! thanks

**Comment by taenri** [comment]
@WoLewicki - Just curious, about when can we expect the next version update to be published?

**Comment by WoLewicki** [comment]
I haven't planned the release soon, but you can always get those changes with a [patch-package](https://www.npmjs.com/package/patch-package) to be able to use them in current version 🚀

**Comment by taenri** [comment]
> I haven't planned the release soon, but you can always get those changes with a [patch-package](https://www.npmjs.com/package/patch-package) to be able to use them in current version 🚀

Wow, I have never heard of this before. Looks awesome, thanks for the tip!

**Pull request merged**
