### PR TITLE
enable buildConfig generation to better support AGP8

### PR DESCRIPTION
**Pull request by pvegh**
So that consumer projects don't have to globally enable this themselves leading to performance impact

# Summary

Since AGP8 this flag is disabled by default. Consumer projects have to enable this flag in them **globally** if the library doesn't do this correctly itself, but uses custom buildConfig fields.

* What issues does the pull request solve? Please tag them so that they will get automatically closed once the PR is merged
Solves Build Errors with default setup using AGP8+
* What is the feature? (if applicable)
No errors and better build performance than the workaround in consuming projects would be.
* How did you implement the solution?
* What areas of the library does it impact?

## Test Plan

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    N/A     |
| Android |    ✅     |

## Checklist

- [ x ] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md`
- [ ] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Comment by pvegh** [comment]
See the same patch in https://github.com/software-mansion/react-native-gesture-handler/issues/2571 which is already merged.

**Comment by pvegh** [comment]
Can we get a new version with this please, so we can remove the global BuildConfig generation and save some build time?

**Review by WoLewicki — APPROVED** [review]
LGTM :rocket: Thanks for your contribution!

**Comment by mikehardy** [comment]
@pvegh thanks for proposing this! I was about to propose the same thing hopefully it is released soon

One question - I notice you wrapped this check in an AGP8+ conditional, any reason for that? Should be supported fine on AGP7+ and similar ones I've proposed do in fact build fine: https://github.com/th3rdwave/react-native-safe-area-context/pull/455

That said, nothing wrong with it technically

One note though, you mention this:

> Can we get a new version with this please, so we can remove the global BuildConfig generation and save some build time?

In my experience at least I needed it at the top-level *and* module level for it to work on AGP8+, where ever buildConfig was used

Cheers

**Comment by pvegh** [comment]
Yeah check for 7+ should work fine. I didn't see the necessity/advantage since only AGP8+ forces us to enable the flag for the whole project in cases like this, when there is at least one module not defining buildConfig for itself.
From 8 on the BuildConfig generation is off by default.

**Comment by mikehardy** [comment]
In my experience, my project wouldn't compile with AGP8 even *with* the global flag, unless the specific modules that needed buildConfig=true had it as well. I needed both, not one or the other 🤔 
Glad I understand the compatibility constraints though (AGP7 vs 8) - I've made PRs to a few repos with this and normally slipstream it in on their existing AGP7 conditional for compatibility

**Comment by pvegh** [comment]
Should work if you put it in the project gradle.properties, but maybe I don't remember every workaround I made for it. AGP8 was a hard nut for sure.

**Pull request merged**
