### PR TITLE
Implement mask-type property

### PR DESCRIPTION
**Pull request by SergeyYurkevich**
# Summary

"mask-type: alpha" is not supported. 
resolve issue: #1790  

## Explanation

svg example:
```
<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100" fill="none">
<g clip-path="url(#clip0_8_3)">
<rect width="100" height="100" fill="white"/>
<mask id="mask0_8_3" mask-type="alpha" maskUnits="userSpaceOnUse" x="0" y="0" width="100" height="100">
<circle cx="50" cy="50" r="50" fill="#000000"/>
</mask>
<g mask="url(#mask0_8_3)">
<rect x="-26" y="-78" width="209" height="263" fill="#252E74"/>
</g>
</g>
<defs>
<clipPath id="clip0_8_3">
<rect width="100" height="100" fill="white"/>
</clipPath>
</defs>
</svg>
```

Current behavior: 
image

Expected behavior:
image

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅    |
| Android |    ✅    |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md`
- [x] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Comment by bohdanprog** [comment]
Hello @SergeyYurkevich,
Could you check how it behaves now?
I guess our last changes were fixed the issue.

Thank you

**Review by jakex7 — APPROVED** [review]
Thank you for your contribution! 🎉
I've added a support for the new architecture, so now I think we're good to go 😄

**Comment by DorianMazur** [comment]
This is still not working on react-native 0.74.4 with new architecture enabled.

**Comment by bohdanprog** [comment]
Hello @DorianMazur,
can you provide a simple example with you problem?

Thank you

**Pull request merged**
