### PR TITLE
Include proguard config

### PR DESCRIPTION
**Pull request by heroic**
# Summary

This will remove the requirement for people to add the proguard configs themselves. A lot of people first release to production with proguard and then realize why the app crashes. This will solve such issues.

This uses android's consumer proguard setting to enable specific proguard config.

## Test Plan

Example app works. All tests pass.

### What's required for testing (prerequisites)?

Example app works. All tests pass.

### What are the steps to reproduce (after prerequisites)?

Proguard enabled release should work without any manual edits to proguard file in the app.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added documentation in `README.md`
- [ ] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Comment by heroic** [comment]
@msand @WoLewicki, can you also release with this for `12.*`?

**Comment by WoLewicki** [comment]
@heroic thanks for your contribution! As for releasing it for `12.*`, I think it is no longer necessary since `13.*` should be stable right now. Or am I missing something?

**Comment by heroic** [comment]
> @heroic thanks for your contribution! As for releasing it for `12.*`, I think it is no longer necessary since `13.*` should be stable right now. Or am I missing something?

not sure what's the status of expo with 13.*

**Comment by WoLewicki** [comment]
Expo SDK 47 features version `13.4.0` of the library so it should be ok.

**Pull request merged**
